# Generated by Django 5.1.1 on 2024-09-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='news_videos/')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
