# Generated by Django 5.1.1 on 2024-09-22 23:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRPayment',
            fields=[
                ('pmid', models.AutoField(primary_key=True, serialize=False)),
                ('outstanding', models.IntegerField(default=0)),
                ('paid', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_payments', to='accounts.patient')),
            ],
        ),
    ]
