# Generated by Django 5.1.1 on 2024-09-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_reception_appointment_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reception',
        ),
    ]
